---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-node-feature-discovery-charts
        namespace: flux-system
      interval: 30m
  values:
    master:
      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: "node-role.kubernetes.io/master"
                    operator: In
                    values: [""]

      resources:
        requests:
          cpu: 23m
          memory: 64M
        limits:
          memory: 64M

    worker:
      annotations:
        configmap.reloader.stakater.com/reload: node-feature-discovery-worker-conf

      config:
        core:
          labelSources:
            - custom
            - pci
            - usb

        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0a"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - "class"
              - "vendor"
              - "device"

          custom:
            - name: zwave
              matchOn:
                - usbId:
                    class: ["02"]
                    vendor: ["0658"]
                    device: ["0200"]

            - name: "intel-gpu"
              matchOn:
                - pciId:
                    class: ["0300"]
                    vendor: ["8086"]

            - name: "coral-tpu"
              matchOn:
                - usbId:
                    vendor: ["1a6e", "18d1"]

      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 64M

      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
