---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: rook
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/rook/rook.git
  ref:
    tag: v1.10.7
  ignore: |
    # exclude all
    /*
    # include crd file
    !/deploy/examples/crds.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-crds
  namespace: flux-system
spec:
  interval: 30m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: rook
