---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  TERRAFORM_DIR: "{{.PROJECT_DIR}}/provision/terraform"

dotenv: [".config.env"]

env:
  KUBECONFIG: "{{.PROJECT_DIR}}/provision/kubeconfig"

includes:
  cluster: .taskfiles/ClusterTasks.yml
  precommit: .taskfiles/PrecommitTasks.yml
  pxe: .taskfiles/PXETasks.yml
  talos: .taskfiles/TalosTasks.yml
  terraform: .taskfiles/TerraformTasks.yml
  rook: .taskfiles/RookTasks.yml
  sops: .taskfiles/SopsTasks.yml
