---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - ./secrets.sops.yaml
  - ./helm-release.yaml
patchesStrategicMerge:
  - ./patches/env.yaml
  - ./patches/postgres.yaml
configMapGenerator:
  - name: authelia-configmap
    files:
      - ./config/configuration.yml
generatorOptions:
  disableNameSuffixHash: true
