---
clusterName: home-ops
talosVersion: v1.3.1
kubernetesVersion: v1.26.0

domain: ${clusterDomainName}
endpoint: "https://home-ops.${mgmtDomainName}:6443"
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/16

additionalApiServerCertSans:
  - ${clusterEndpointIP}

additionalMachineCertSans:
  - ${clusterEndpointIP}
  - home-ops.${mgmtDomainName}
  - home-ops.${clusterDomainName}

cniConfig:
  name: none

nodes:
  - hostname: polaris.${mgmtDomainName}
    ipAddress: 10.99.1.100
    controlPlane: true
    installDisk: /dev/nvme0n1
    nameservers:
      - 10.99.0.1
      - 1.1.1.1
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 10.99.1.100/16
        vip:
          ip: ${clusterEndpointIP}
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.99.0.1
        vlans:
          - vlanId: 50
            dhcp: false
            mtu: 1500
      - interface: eth1
        dhcp: false
        ignore: true
      - interface: eth2
        dhcp: false
        mtu: 9000
        vlans:
          - vlanId: 20
            mtu: 9000
            dhcp: false
      - interface: eth3
        dhcp: false
        ignore: true
    inlinePatch:
      machine:
        install:
          extensions:
            - image: ghcr.io/siderolabs/intel-ucode:20221108

  - hostname: vega.${mgmtDomainName}
    ipAddress: 10.99.1.101
    controlPlane: true
    installDisk: /dev/sda
    nameservers:
      - 10.99.0.1
      - 1.1.1.1
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 10.99.1.101/16
        vip:
          ip: ${clusterEndpointIP}
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.99.0.1
        vlans:
          - vlanId: 50
            dhcp: false
            mtu: 1500
      - interface: eth1
        dhcp: false
        mtu: 9000
        vlans:
          - vlanId: 20
            mtu: 9000
            dhcp: false
    inlinePatch:
      machine:
        install:
          extensions:
            - image: ghcr.io/siderolabs/intel-ucode:20221108

  - hostname: capella.${mgmtDomainName}
    ipAddress: 10.99.1.102
    controlPlane: true
    installDisk: /dev/nvme0n1
    nameservers:
      - 10.99.0.1
      - 1.1.1.1
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 10.99.1.102/16
        vip:
          ip: ${clusterEndpointIP}
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.99.0.1
        vlans:
          - vlanId: 50
            dhcp: false
            mtu: 1500
      - interface: eth1
        dhcp: false
        mtu: 9000
        vlans:
          - vlanId: 20
            mtu: 9000
            dhcp: false
    inlinePatch:
      machine:
        install:
          extensions:
            - image: ghcr.io/siderolabs/intel-ucode:20221108

  - hostname: rigel.${mgmtDomainName}
    ipAddress: 10.99.1.103
    controlPlane: false
    installDisk: /dev/nvme0n1
    nameservers:
      - 10.99.0.1
      - 1.1.1.1
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 10.99.1.103/16
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.99.0.1
        vlans:
          - vlanId: 50
            dhcp: false
            mtu: 1500
      # - interface: eth1
      #   dhcp: false
      #   mtu: 9000
      #   vlans:
      #     - vlanId: 20
      #       mtu: 9000
      #       dhcp: false
    inlinePatch:
      machine:
        install:
          extensions:
            - image: ghcr.io/siderolabs/intel-ucode:20221108

controlPlane:
  inlinePatch:
    cluster:
      allowSchedulingOnMasters: true
      apiServer:
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      controllerManager:
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      discovery:
        registries:
          service:
            disabled: true
      proxy:
        disabled: true
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      scheduler:
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True

    machine:
      files:
        - path: /etc/cri/conf.d/20-customization.part
          op: create
          content: |
            [plugins]
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
      kubelet:
        extraArgs:
          feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true,EphemeralContainers=True
          rotate-server-certificates: "true"
      install:
        extraKernelArgs:
          - "talos.logging.kernel=udp://vector.${ingressDomain}:6050/"
      logging:
        destinations:
          - endpoint: "udp://vector.${ingressDomain}:6051/"
            format: json_lines
      network:
        extraHostEntries:
          - ip: ${clusterEndpointIP}
            aliases:
              - home-ops.${mgmtDomainName}
              - home-ops.${clusterDomainName}
      sysctls:
        fs.inotify.max_user_watches: "1048576"
        fs.inotify.max_user_instances: "8192"
      time:
        disabled: false
        servers:
          - 10.99.0.1

worker:
  inlinePatch:
    cluster:
      discovery:
        registries:
          service:
            disabled: true

    machine:
      files:
        - path: /etc/cri/conf.d/20-customization.part
          op: create
          content: |
            [plugins]
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
      kubelet:
        extraArgs:
          feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true,EphemeralContainers=True
          rotate-server-certificates: "true"
      install:
        extraKernelArgs:
          - "talos.logging.kernel=udp://vector.${ingressDomain}:6050/"
      logging:
        destinations:
          - endpoint: "udp://vector.${ingressDomain}:6051/"
            format: json_lines
      network:
        extraHostEntries:
          - ip: ${clusterEndpointIP}
            aliases:
              - home-ops.${mgmtDomainName}
              - home-ops.${clusterDomainName}
      sysctls:
        fs.inotify.max_user_watches: "1048576"
        fs.inotify.max_user_instances: "8192"
      time:
        disabled: false
        servers:
          - 10.99.0.1
