---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml

  - ./goldilocks/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
  - ./scrutiny/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./speedtest-exporter/ks.yaml
  - ./thanos/ks.yaml
  - ./vector/ks.yaml
  - ./vpa/ks.yaml
