---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    kustomize.toolkit.fluxcd.io/prune: enable
    goldilocks.fairwinds.com/enabled: "true"
    secret.home.arpa/postgres-superuser: "true"
