---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/gitrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: k8snetworkplumbingwg-helm-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/k8snetworkplumbingwg/helm-charts.git
  ref:
    branch: master
