---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-storage-rook-ceph-operator
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./cluster/apps/storage/rook-ceph/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-storage-rook-ceph-cluster
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-storage-rook-ceph-operator
  interval: 10m
  path: ./cluster/apps/storage/rook-ceph/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-storage-rook-ceph-config
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-storage-rook-ceph-cluster
  interval: 10m
  path: ./cluster/apps/storage/rook-ceph/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-storage-rook-ceph-toolbox
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-storage-rook-ceph-cluster
  interval: 10m
  path: ./cluster/apps/storage/rook-ceph/rook-direct-mount
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-storage-rook-ceph-grafana-dashboard
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-storage-rook-ceph-cluster
  interval: 10m
  path: ./cluster/apps/storage/rook-ceph/dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
