{
    "data": "ENC[AES256_GCM,data:WY2eNBUQV4nZEMbVJXsL6AxmR5jz/eKpuvDB35bAJUmTzfmVbCt9UazLWmGXo9RgMCr8R04r2QzeSzGXTKY3rPPodGMtox4A21/vEgy8mTTEswp+xeQImWjJpmQl5+LfKL/w2BtUIbmuBpSoMxEAFW2FobmaDCeEnw3my1Xcc9HREZGVXarksi3ZttYPlOg57SO/aXMeKSzxtUFPgqYk7zgroeDxhQD4YS45rHutuvWyS8B/tH8R3+CblCLVW/767p9TKmcquEJ559ddRGzKvadG0AnDFb4V3X8EAKYXOxA5HCtZ/KZpCbboOfdmsQrgcSYBexd3BmP+/rAkRIisPq0VFXPdP+mHQQBIQEje4Mys4HkPco1CWOPzMiEQhtBUTUAZgzhkv1N0f/QWlbILhIuXPKd9n9oF7mW20kGyfPQcvfwQ/INGbFGVHvPAuql+1wCIUgdQphscrc+Mc3FCCRk1ejOgv7N+xHAT2pyij2jjdzgFrscUU9F5Qn4HaJxc5Ht2DnwX1yWYLL9HAVifF6FPMuBFwnLkwwGE9iDcc+plmhO6ylETNTxnSFFFx+3i2K4yovqDXZQm+fz5gR507/6AbvjtmZJ2VwT/XvYPq6dT649NX3h+VGqQhhxI6YI/x2KHbOihqSB2D9K4XfgpAxQ8G3y9DuqchzoAOQeAsYsjrokCwuNjzIuhtEH+FVzDhc9biof6rwtrhID+sVbw475ultCGHd6S31bwvw7XRU+qOyrLmNM06RmmuSmLwmH0QsgB9KWdDlZzhcWYOf8AgDi9kuQw0oyLa9Q=,iv:yI7Nl9oPDlp96SAPnQ5jxihfSsFKxX0WPW40gmLK1EM=,tag:fMV34g5mtphmRk5kygY72w==,type:str]",
    "sops": {
        "kms": null,
        "gcp_kms": null,
        "azure_kv": null,
        "hc_vault": null,
        "age": [
            {
                "recipient": "age1sygu27jssadvgjm86dm0h7p02yzqnp2naxaz3mjrkc4tkek9a35sthss8w",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSTdkQ3ZxSUtzU1Rwbmhv\nZTRDNFM2QXZMdG1jSWZCakk2K3JKL0lOYzNrCjdYTVJDeXFKUlUrSCtCMjRnUzJR\nOTdXNTk4NG5YekNub2c2em0ySzBqZWcKLS0tIFczSHVrRmhZUk0wZmtmV1ZQUGF1\ncHh4aEc2QVBOQU5GbUlla2w1YTYzeUkKmO4E8HjCoUr5BnRKM6DGQ0L3GOJIpXbB\nTvy2Bvh+Pome3uDejeHR6hdwFXP/jAEFcjZhp3hpkC1Kyk/e1mfJ5Q==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2022-12-12T03:56:15Z",
        "mac": "ENC[AES256_GCM,data:YtgUkccR36UN7aGN78uwGRE4iwUcSEKjlGZvwtg6+a5yc7+qjXg3QO+VWih9cCMsqDm1IlH7E+Z/nTdWok5kd6rJEmYOcaSaGL7OVeLkfT8pQeHYCMRda7Z5hvvfXwlR2IONapZSFMVnrnY+FWR5XHjl5KMpizuDfZ8kIpbgQkw=,iv:MFlaipKYhab85RHPufEneH8SCQI1pIaBHZSn2i+Lq/4=,tag:H4ee9AKTdZ4JrF2jxuJQ6g==,type:str]",
        "pgp": null,
        "unencrypted_suffix": "_unencrypted",
        "version": "3.7.3"
    }
}
