{
    "data": "ENC[AES256_GCM,data:J41uGM+m1QPZ+pi4CWBKty9vgCJggNk+gk5cOdZHo2Q9ReCvDSi++rKwcJwrHnCiw7wl3Oj9yYQTJ2T72DBpEo3ZSoLvWjMbmEY/K1MXT1WTtzXnKKciwZuU9O16ru1O/bDu6J4FlTfdSlIZYbHn9Ohpqj+r1CzjZ2qM0PKseOyXyiwcAEN86/S1vtew2sjd9qnUTDXn3/EzgXdJzl5RjW+QpANp/H70kGIsHcex6ESsorRbCl3pIDuBJXwlAh40T2+DobIO4CpMHYfoVeorDpbRAiwKdGBCK7FjSSKtMb4pQp241iWDPvsvhEO/aPZ1/EgbOKredGxSv2JLOeEMtfwRexmBArW8FibvO0IvgPBeLHLRAq9+ZwsJ51mr1eFDPgUbW/S1C+ZMIhAExSMtRM4+SVKCuF3Mq4gcHSyR+JNzAicFoPhe8ZFZP2GXJoW0HoqET/W51t/Na5zxOL1voAjvREjRoG/O0bkj/gxHQR3A01rqI+Fe3mVlXvaPJsucReLOrvNPAj+o6q0MwwhydGiuho5kluP7hm2qXkMK7l5l7uEsrJILi59oNvPomgSWwkpQ9dhaVeubocrDZD6g7kA2qoTFlLa17r2GX/WxEgHZX8gFXgcEr3hwJOXQbcBZNJQwqIyOXNjqrCyj5T34p8crsWdvfv+cHr33Xgm1HorqdTWqb/KcXDzsbl9pootmFyWhOjmGqkiF4qEdybMQd3yJ0N6m7TlfHzr39MBgBdIftffHUezfivA91ZsEuBpLNmG0ISws292FNJsFWu1firHPJVHli05DvkT3QcHnxGn5IE31zRvJr7GTUl5I3oKKkRC1g8dmnfgrxCPXSOAkWfTX+86b0uBBxEjyIzfb/n9WckOZTkP0/iAAVXvD4vLlDQ==,iv:JfBg/y1UJZSupEVsd2IVTyPfHZSHkJfpwuJtbHhQTuI=,tag:1q0beZwXU1qxyGRAvub57Q==,type:str]",
    "sops": {
        "kms": null,
        "gcp_kms": null,
        "azure_kv": null,
        "hc_vault": null,
        "age": [
            {
                "recipient": "age1sygu27jssadvgjm86dm0h7p02yzqnp2naxaz3mjrkc4tkek9a35sthss8w",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSTdkQ3ZxSUtzU1Rwbmhv\nZTRDNFM2QXZMdG1jSWZCakk2K3JKL0lOYzNrCjdYTVJDeXFKUlUrSCtCMjRnUzJR\nOTdXNTk4NG5YekNub2c2em0ySzBqZWcKLS0tIFczSHVrRmhZUk0wZmtmV1ZQUGF1\ncHh4aEc2QVBOQU5GbUlla2w1YTYzeUkKmO4E8HjCoUr5BnRKM6DGQ0L3GOJIpXbB\nTvy2Bvh+Pome3uDejeHR6hdwFXP/jAEFcjZhp3hpkC1Kyk/e1mfJ5Q==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2022-12-13T16:07:21Z",
        "mac": "ENC[AES256_GCM,data:zEEANKWtJP7VZErbVbJeyZPNQ1qUKsgmV1Xvb+KWdD91lrUrwcO6g18mO9rhZHyoaWPaXGItaitu8Z3WgeCdW3L1A7yv/pIFrJdd4uoH0RyUqYGH0uDD+QpUSOTbXDnjnWrOk1pc8lsNNjOszB/sD3qw5eb9g/4/FK+oDLKFRGQ=,iv:2f5x/PXniHLywFI+vUCIL4KuL66yBmFsZj/PeHX6+AA=,tag:RiJ2htvkDzEILxPabqNY8w==,type:str]",
        "pgp": null,
        "unencrypted_suffix": "_unencrypted",
        "version": "3.7.3"
    }
}
