{
    "data": "ENC[AES256_GCM,data:P+0WIrUOw8VplePsisqnjBWySo08FJFkomHc46koMur8IIKRuBTP3HO40d1mqhyFm/YT4TcNam/I2FeZw1y4UWiI2ycTJiyXBe+BHQww1giLKC2jkz4rterOGYvxVHkdvmUG+9P3y3YQsb8LcNWaN1893tSOEWoKDj4k/A45hPjqh51auHzei7yKjqynNh1vCoSa9ChpjNSzaXztbtOzch5ycHsA4zMeajui0DnZIUwFvm8rxx4a8GYXA3/jGz3bXazc+nZZkuNlU4zsor9xZjpVO3+iyNkKGwKAGNa69X3oX2SDYHErIzkQAJ7EIgGDsiLN5MY/DLpY2oRgKipI99oqn4c1UPvTUQ7RuXa44d9GlDrbhcaX+qSNV9ZEERF+tbmmzISE7BExJzGgKeDmaiLmFKLBmOXvF5cwjrgL1xi29LjNaxoRX9qrcFodoTUhvJ9JLVpZwXimGdfxqO72wz5I4fmH5/QPul2d0KjGdvK0rE5vZxUTylyM61cyyRolqtYbBYLi1PJL2wX4slU9Qv8t2bBlVeQ6lbT8b90CFsFjNzXWvRfQnDIrv3ENfPqJwBZoHbSwUkw55It6adcszTtArRvKyg0J902ssHlzCxZipumQxWDqkYvmbX5oYS7BfPbDcTSLK2rp748FqstSj9nu7ZfKdB8OQjz47ICtF2KokbQo9629EuQ7XCzQQIARJ9YDvtUbs9KTG4Sp02zc4mUSqL1TTmWG0NfZ3YtX7kHB2FI3hUm1xwv8Ten+wL8ojE5IM1GYKhEE4bYWc9IRJzcscniPKCvAVIs=,iv:52Zd7+M1kf2y9fpQGUTEjj9+SOXA8TzSrGOF8/hYT1E=,tag:Jz3KzjtE0M2avBvQgL3aIw==,type:str]",
    "sops": {
        "kms": null,
        "gcp_kms": null,
        "azure_kv": null,
        "hc_vault": null,
        "age": [
            {
                "recipient": "age1sygu27jssadvgjm86dm0h7p02yzqnp2naxaz3mjrkc4tkek9a35sthss8w",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSTdkQ3ZxSUtzU1Rwbmhv\nZTRDNFM2QXZMdG1jSWZCakk2K3JKL0lOYzNrCjdYTVJDeXFKUlUrSCtCMjRnUzJR\nOTdXNTk4NG5YekNub2c2em0ySzBqZWcKLS0tIFczSHVrRmhZUk0wZmtmV1ZQUGF1\ncHh4aEc2QVBOQU5GbUlla2w1YTYzeUkKmO4E8HjCoUr5BnRKM6DGQ0L3GOJIpXbB\nTvy2Bvh+Pome3uDejeHR6hdwFXP/jAEFcjZhp3hpkC1Kyk/e1mfJ5Q==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2022-12-12T02:45:21Z",
        "mac": "ENC[AES256_GCM,data:cz28Ww1FjReMdOZtlGbTOjhWJJyTWnrGiMF106dzvHBpx+0jkVTPkdkq+XHQwbStO39RD9O0CB0lqSxp6BpTExVaCQa7WwdpkAMOdUOChQQitmCH1Phs2ryPyL2ULkxUTSZk5ata76X3rc1yDNUgV4mZI0pwvrkW2MB2Kr51u4o=,iv:QanJawgnzG8m5dd3+4H7CwDDwegH5/rojrwamtlhxk4=,tag:8MVmxWTLgLtC/S5XC9MJ6w==,type:str]",
        "pgp": null,
        "unencrypted_suffix": "_unencrypted",
        "version": "3.7.3"
    }
}
