---
- name: Cluster Rook-Ceph Nuke
  hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 2
  tasks:
    - name: Reset disks # noqa ignore_errors
      ignore_errors: true
      block:
        - name: Remove /var/lib/rook
          ansible.builtin.file:
            state: absent
            path: /var/lib/rook
        - name: Zap the drives # noqa
          ansible.builtin.shell: |-
            sgdisk --zap-all {{ item }} || true
          loop:
            - "{{ rook_devices | default([]) }}"
        - name: Remove lvm partitions # noqa
          ansible.builtin.shell: |-
            {{ item }}
          loop:
            - ls /dev/mapper/ceph--* | xargs -I% -- fuser --kill %
            - ls /dev/mapper/ceph--* | xargs -I% -- dmsetup clear %
            - ls /dev/mapper/ceph--* | xargs -I% -- dmsetup remove -f %
            - ls /dev/mapper/ceph--* | xargs -I% -- rm -rf %
        - name: Wipe the block device # noqa
          ansible.builtin.command: |-
            wipefs --all --force {{ item }}
          with_items:
            - "{{ rook_devices | default([]) }}"
