---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kyverno-app
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./cluster/apps/kyverno/kyverno/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kyverno
      namespace: kyverno
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kyverno-policies
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-kyverno-app
  interval: 10m
  timeout: 2m
  retryInterval: 1m
  path: ./cluster/apps/kyverno/kyverno/policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
