---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: storage-network
  namespace: rook-ceph
spec:
  config: '{
            "cniVersion": "0.3.1",
            "name": "storage-network",
            "type": "macvlan",
            "mode": "bridge",
            "master": "vlan20",
            "mtu": 9000,
            "ipam": {
                "type": "whereabouts",
                "range": "10.0.20.0/24",
                "exclude": [
                  "10.0.20.0/28",
                  "10.0.20.100/28",
                  "10.0.20.254/32"
                ]
            }
        }'
