---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app loki
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph

  values:
    loki:
      revisionHistoryLimit: 3

      structuredConfig:
        auth_enabled: false

        querier:
          engine:
            timeout: 5m
          query_timeout: 5m

        frontend:
          max_outstanding_per_tenant: 4096

        query_range:
          parallelise_shardable_queries: false
          cache_results: true
          results_cache:
            cache:
              enable_fifocache: true
              fifocache:
                max_size_items: 1024
                validity: 24h

        server:
          log_level: info
          http_listen_port: 3100
          grpc_listen_port: 9095
          grpc_server_max_concurrent_streams: 250
          grpc_server_max_recv_msg_size: 10485760000
          grpc_server_max_send_msg_size: 10485760000
          http_server_write_timeout: 10m
          http_server_read_timeout: 10m
          http_server_idle_timeout: 10m
          graceful_shutdown_timeout: 2m

        memberlist:
          join_members: ["loki-memberlist"]

        common:
          path_prefix: /var/loki
          replication_factor: 3
          storage:
            s3:
              s3: null
              insecure: true
              s3forcepathstyle: true
          ring:
            kvstore:
              store: memberlist

        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          max_cache_freshness_per_query: 10m
          split_queries_by_interval: 15m

          retention_period: 168h
          max_query_lookback: 168h
          max_query_series: 5000
          max_query_parallelism: 5000
          max_streams_matchers_per_query: 10000
          max_entries_limit_per_query: 2500000
          ingestion_rate_mb: 16
          ingestion_burst_size_mb: 32
          per_stream_rate_limit: "40MB"
          per_stream_rate_limit_burst: "80MB"
          shard_streams:
            enabled: true

        schema_config:
          configs:
            - from: "2022-01-11"
              store: boltdb-shipper
              object_store: s3
              schema: v12
              index:
                prefix: loki_index_
                period: 24h

        ruler:
          enable_api: true
          enable_alertmanager_v2: true
          alertmanager_url: http://kube-prometheus-stack-alertmanager:9093
          storage:
            type: local
            local:
              directory: /rules
          rule_path: /tmp/scratch
          # ring:
          #   kvstore:
          #     store: memberlist

        ingester:
          max_chunk_age: 1h
          # lifecycler:
          #   ring:
          #     kvstore:
          #       store: memberlist

        compactor:
          working_directory: /var/loki/boltdb-shipper-compactor
          shared_store: s3
          compaction_interval: 10m
          retention_enabled: true
          retention_delete_delay: 2h
          retention_delete_worker_count: 150

        # distributor:
        #   ring:
        #     kvstore:
        #       store: memberlist

        analytics:
          reporting_enabled: false

    # Configuration for the write pod(s)
    write:
      replicas: 3
      affinity: |
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "loki.writeSelectorLabels" . | nindent 10 }}
                topologyKey: kubernetes.io/hostname

      persistence:
        size: 10Gi
        storageClass: ceph-block

    # Configuration for the read pod(s)
    read:
      replicas: 3
      affinity: |
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "loki.readSelectorLabels" . | nindent 10 }}
                topologyKey: kubernetes.io/hostname

      # extraVolumeMounts:
      #   - name: loki-rules
      #     mountPath: /rules/fake
      #   - name: loki-rules-tmp
      #     mountPath: /tmp/scratch
      #   - name: loki-tmp
      #     mountPath: /tmp/loki-tmp

      # extraVolumes:
      #   - name: loki-rules
      #     configMap:
      #       name: loki-alerting-rules
      #   - name: loki-rules-tmp
      #     emptyDir: {}
      #   - name: loki-tmp
      #     emptyDir: {}

      persistence:
        size: 10Gi
        storageClass: ceph-block

    # Configuration for the backend pod(s)
    backend:
      replicas: 3
      affinity: |
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "loki.backendSelectorLabels" . | nindent 10 }}
                topologyKey: kubernetes.io/hostname

      extraVolumeMounts:
        - name: loki-rules
          mountPath: /rules/fake
        - name: loki-rules-tmp
          mountPath: /tmp/scratch
        - name: loki-tmp
          mountPath: /tmp/loki-tmp

      extraVolumes:
        - name: loki-rules
          configMap:
            name: loki-alerting-rules
        - name: loki-rules-tmp
          emptyDir: {}
        - name: loki-tmp
          emptyDir: {}

      persistence:
        size: 10Gi
        storageClass: ceph-block

    # Configuration for the gateway
    gateway:
      enabled: true
      replicas: 1
      affinity: |
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "loki.gatewaySelectorLabels" . | nindent 10 }}
                topologyKey: kubernetes.io/hostname

      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "loki.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    # -- Section for configuring optional Helm test
    test:
      enabled: false

    # -- Monitoring section determines which monitoring features to enable
    monitoring:
      serviceMonitor:
        enabled: false
        metricsInstance:
          enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false

  valuesFrom:
    - targetPath: loki.structuredConfig.common.storage.s3.bucketnames
      kind: ConfigMap
      name: loki-chunks-bucket-v1
      valuesKey: BUCKET_NAME

    - targetPath: loki.structuredConfig.common.storage.s3.endpoint
      kind: ConfigMap
      name: loki-chunks-bucket-v1
      valuesKey: BUCKET_HOST

    - targetPath: loki.structuredConfig.common.storage.s3.access_key_id
      kind: Secret
      name: loki-chunks-bucket-v1
      valuesKey: AWS_ACCESS_KEY_ID

    - targetPath: loki.structuredConfig.common.storage.s3.secret_access_key
      kind: Secret
      name: loki-chunks-bucket-v1
      valuesKey: AWS_SECRET_ACCESS_KEY
