---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-intel-gpu-plugin
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./cluster/apps/kube-system/intel-gpu-plugin/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-intel-gpu-exporter
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./cluster/apps/kube-system/intel-gpu-plugin/exporter"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
  dependsOn:
    - name: cluster-apps-intel-gpu-plugin
