---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg-operator
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./kubernetes/apps/databases/cloudnative-pg/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg-config
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg-operator
  interval: 10m
  path: ./kubernetes/apps/default/cloudnative-pg/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
