---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-external-dns
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./cluster/apps/network/external-dns/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
