---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disable-prometheus-rules
  annotations:
    policies.kyverno.io/title: Disable Prometheus Rules
    policies.kyverno.io/subject: PrometheusRules
    policies.kyverno.io/description: >-
      This policy applies a disabled label to select prometheus rules.
spec:
  background: true
  mutateExistingOnPolicyUpdate: true
  schemaValidation: false
  rules:
    - name: prometheus-kubevirt-rules
      match:
        any:
          - resources:
              kinds:
                - PrometheusRule
              names:
                - prometheus-kubevirt-rules

      preconditions:
        all:
          - key: "{{ request.object.spec.groups[0].name || '' }}"
            operator: Equals
            value: "kubevirt.rules"
          - key: "{{ request.object.spec.groups[0].rules[36].alert || ''}}"
            operator: Equals
            value: "KubeVirtComponentExceedsRequestedMemory"

      mutate:
        targets:
          - kind: PrometheusRule
            name: "{{ request.object.metadata.name }}"
            namespace: "{{ request.object.metadata.namespace }}"
        patchesJson6902: |-
          - path: /spec/groups/0/rules/36
            op: remove
