---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      chart: k8s-gateway
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    fullnameOverride: k8s-gateway
    domain: ${SECRET_DOMAIN}
    ttl: 1
    service:
      annotations:
        reloader.stakater.com/auto: "true"
      type: LoadBalancer
      port: 53
      loadBalancerIP: "${SVC_K8S_GATEWAY_ADDRESS}"
      externalTrafficPolicy: Local
