---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-scrutiny
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./cluster/apps/monitoring/scrutiny/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
