# https://github.com/AnalogJ/scrutiny/blob/master/docker/example.hubspoke.docker-compose.yml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scrutiny
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    # createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: ingress-nginx
      namespace: kube-system
    - name: scrutiny-influxdb
      namespace: monitoring
  values:
    image:
      repository: ghcr.io/analogj/scrutiny
      tag: master-web

    env:
      TZ: "${TIMEZONE}"
      SCRUTINY_WEB_INFLUXDB_HOST: scrutiny-influxdb.monitoring.svc.cluster.local

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          # auth.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: harddisk
        hosts:
          - host: &host "scrutiny.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    service:
      main:
        ports:
          http:
            port: &port 8080

    probes:
      liveness: &health
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: *port
      readiness: *health
      startup:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 30
          httpGet:
            path: /api/health
            port: *port

    persistence:
      config:
        enabled: true
        # existingClaim: scrutiny-data
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi
        mountPath: /opt/scrutiny/config
        subPath: scrutiny

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi
