# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: network
stringData:
    api-key: ENC[AES256_GCM,data:2pthTnetLVuanOq0WO6L3FtSxlA2w7wggiPJZIQcx+IDfi+sCA==,iv:VIiwJD8A/HWrR13wRudGAJ3T0zt4IZzVZO1lP4xhNIg=,tag:bozJMwzlYGoIiC1G2h3gzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sygu27jssadvgjm86dm0h7p02yzqnp2naxaz3mjrkc4tkek9a35sthss8w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRWEwc2tLU0pWd0oxWCtY
            ODd4MzI3aFF1dUpkNUNrVDhlRjdNUG1HN0g4Cjh3U1Ricmg0N2tQeXlBNSt6WUFR
            dkpBaVVKUG5obGpOeEliM0FzY09QbEUKLS0tIGw0c0l2cnBGUnV6QkFaaWFFRmU3
            WjZoQkxnZStlbi9oUGFMeDhicndLc0kKmhjNYbTd19PB7RUHCqxy0bSVpuTP+Ed+
            EmHf93VFbugx6DejlCiB6p9Ix3wAFazojKwVd89smpWxAdBblBRfzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-20T15:05:12Z"
    mac: ENC[AES256_GCM,data:FKUNqjEAi2AxQJ+JuBpwHxxTQyMUpaToAo0kxGKAJiSFRdXXOcz02wTNbHGvZQRifx8ekiVfvEBuAd0cS7CzFQCUhq5JSol9qrn9taQdvk3k8XoHcaACzYcim3Mfd29iEvLyb+Yi3jV/iYvLlYzu1sE5ErnR5lxiAtSDRz++jXc=,iv:rfvNVp3EPnY94WHy5oXgLGHmgW778FAwZwFmotYfEV0=,tag:mrQkqXiJ4xxJZvFTGt+3hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
