---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 15m
  chart:
    spec:
      chart: kyverno
      version: 2.7.0-rc.4
      sourceRef:
        kind: HelmRepository
        name: kyverno-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    installCRDs: true
    replicaCount: 1 # as of 1.9.0-rc.2 HA is broken with mutate rules see (https://github.com/kyverno/kyverno/issues/5848), should be fixed in 1.10
    serviceMonitor:
      enabled: true

    # updateStrategy:
    #   type: RollingUpdate
    #   rollingUpdate:
    #     maxSurge: 1

    resources:
      requests:
        cpu: 250m
        memory: 512M
      limits:
        memory: 1280M

    # topologySpreadConstraints:
    #   - maxSkew: 1
    #     topologyKey: kubernetes.io/hostname
    #     whenUnsatisfiable: DoNotSchedule
    #     labelSelector:
    #       matchLabels:
    #         app.kubernetes.io/instance: kyverno
