---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./auth
  # - ./databases
  # - ./default
  - ./kube-system
  - ./kyverno
  # - ./monitoring
  - ./network
  # - ./storage
  # - ./system-upgrade
