---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: network
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/apps/network
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
