---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
        - ExpandDisks
        - CPUManager
        - GPU
        - HostDevices
      memoryOvercommit: "150"
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
  monitorNamespace: monitoring
  monitorAccount: kube-prometheus-stack-operator
