---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-releases depName=kubevirt/kubevirt
  - https://github.com/kubevirt/kubevirt/releases/download/v0.58.0/kubevirt-operator.yaml
  # renovate: datasource=github-releases depName=kubevirt/containerized-data-importer
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.55.2/cdi-operator.yaml
  - ./kubevirt-cr.yaml
  - ./cdi-cr.yaml
  - ./patches/sp-ceph-block.yaml
  - ./patches/sp-ceph-bucket.yaml
  - ./patches/sp-ceph-fs.yaml
  - ./patches/pr-kubevirt-rules.yaml
