# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: redis
    namespace: databases
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:+ai1tkC4ajztaCMhZx2JgEOuR9r+6a5HB0xUVs5nESuuyMltliBWgTdtGhaD6kNBaCHTblRCkeGYQVS0Swnnl0MCFlEJUcFKPNtcFQ==,iv:3P/YWjlr/Zkq5RpvwFR0/rQktTImIxRs/Cx8skZL0ow=,tag:y1pfL2Se1H5N6jz+hmeyXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sygu27jssadvgjm86dm0h7p02yzqnp2naxaz3mjrkc4tkek9a35sthss8w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUVJYYm1nTVI4YXovL29t
            ZHpBenpBWldjNzFSMGlYNitubUoybUlTZTJZCm1uQjdNY3Q0TE5IR0hOY3UzZGNS
            c3pjdGJ6Vlp5ZEtKcElpZzRqdk40ejgKLS0tIG5XamNaczhhUnQ1S1V5dFFiRDlv
            MGFXbHhkNVlJcDhpMVdJdGNLMlRUT0EK3csl/YckLNkRDjtCfeYCtKG2PVfwoPr2
            VPUNN7k/09NzhbZj/DiTv4e9GFyFqYiIIrka7uOMnEfJ/PepDbtxSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-12T02:18:31Z"
    mac: ENC[AES256_GCM,data:/w4g6Y7eksOYmNG4skt2WDNOAq5wYZVCRob+vtekv/p26B32TsBf8RVKV468nCQJ4E4Jc4FJlPznQLiqbaRkJmMOpd44iLj2ceZ7JTRHfwlEtNV5WvOkeMy1gzUbG1GCZKo87HESvhnLhwTxZaIcHTlHqzeiKFeLLBzO5EgE0j8=,iv:sB7fMgCjGxGiJD6QrljZ7bsb9u1Nm4/OQtdzV7mlcIY=,tag:6ZZtlDvUIQ8uu8ipc/LUHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
