---
apiVersion: v1
kind: Pod
metadata:
  name: ext-drive
  namespace: rook-ceph

spec:
  containers:
    - name: ext-drive
      image: alpine

      securityContext:
        privileged: true

      nodeSelector:
        feature.node.kubernetes.io/custom-wd-elements: "true"

      volumeMounts:
        - name: device-dir
          mountPath: /dev

      command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]

      resources:
        limits:
          cpu: 2000m
          memory: 4G

  volumes:
    - name: device-dir
      hostPath:
        path: /dev
# kubectl exec -it ext-drive -- /bin/ash
