---
apiVersion: v1
kind: Pod
metadata:
  name: multus-test
  namespace: rook-ceph
  annotations:
    k8s.v1.cni.cncf.io/networks: network/multus-vlan20
spec:
  containers:
    - name: multus-test
      command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
      image: alpine
      resources:
        limits:
          cpu: 2000m
          memory: 4G

# kubectl exec -it multus-test -- /bin/ash
