---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vector
      version: 0.19.0
      sourceRef:
        kind: HelmRepository
        name: vector-charts
        namespace: flux-system
      interval: 15m

  values:
    role: "Stateless-Aggregator"

    podAnnotations:
      configmap.reloader.stakater.com/reload: vector-aggregator

    customConfig:
      data_dir: /vector-data-dir

      api:
        enabled: true
        address: 0.0.0.0:8686

      # Sources
      sources:
        kubernetes_logs:
          address: 0.0.0.0:6000
          type: vector
          version: "2"

        journal_logs:
          type: vector
          address: 0.0.0.0:6002
          version: "2"

        vector_metrics:
          type: internal_metrics

        talos_kernel_logs:
          address: 0.0.0.0:6050
          type: socket
          mode: udp
          max_length: 102400
          decoding:
            codec: json
          host_key: __host

        talos_service_logs:
          address: 0.0.0.0:6051
          type: socket
          mode: udp
          max_length: 102400
          decoding:
            codec: json
          host_key: __host

      # Transformations
      transforms:
        kubernetes_logs_remap:
          type: remap
          inputs:
            - kubernetes_logs
          source: |-
            # Standardize 'app' index
            .app = .kubernetes.pod_labels."app.kubernetes.io/name" || .kubernetes.pod_labels.app || .kubernetes.pod_labels."k8s-app" || .kubernetes.pod_name

        talos_kernel_logs_xform:
          type: remap
          inputs:
            - talos_kernel_logs
          source: |-
            .__host, .err = replace(.__host, "10.99.1.100", "polaris")
            .__host = replace(.__host, "10.99.1.101", "vega")
            .__host = replace(.__host, "10.99.1.102", "capella")
            .__host = replace(.__host, "10.99.1.103", "rigel")
        talos_service_logs_xform:
          type: remap
          inputs:
            - talos_service_logs
          source: |-
            .__host, .err = replace(.__host, "10.99.1.100", "polaris")
            .__host = replace(.__host, "10.99.1.101", "vega")
            .__host = replace(.__host, "10.99.1.102", "capella")
            .__host = replace(.__host, "10.99.1.103", "rigel")

      # Sinks
      sinks:
        loki_kubernetes:
          type: loki
          inputs:
            - kubernetes_logs_remap
          endpoint: http://loki-gateway.monitoring:80
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: rewrite_timestamp
          remove_label_fields: true
          remove_timestamp: true
          labels:
            source: kubernetes_logs
            app: >-
              {{`{{ .app }}`}}
            container: >-
              {{`{{ kubernetes.container_name }}`}}
            filename: >-
              {{`{{ kubernetes.file }}`}}
            namespace: >-
              {{`{{ kubernetes.pod_namespace }}`}}
            node: >-
              {{`{{ kubernetes.pod_node_name }}`}}
            pod: >-
              {{`{{ kubernetes.pod_name }}`}}

        loki_journal:
          type: loki
          inputs:
            - journal_logs
          endpoint: http://loki-gateway.monitoring:80
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            source: journal_logs
            hostname: >-
              {{`{{ host }}`}}

        talos_kernel:
          type: loki
          inputs:
            - talos_kernel_logs_xform
          endpoint: http://loki-gateway.monitoring:80
          encoding:
            codec: json
            except_fields:
              - __host
          batch:
            max_bytes: 1048576
          out_of_order_action: rewrite_timestamp
          labels:
            source: talos_kernel
            hostname: >-
              {{`{{ __host }}`}}
            service: >-
              {{`{{ facility }}`}}

        talos_service:
          type: loki
          inputs:
            - talos_service_logs_xform
          endpoint: http://loki-gateway.monitoring:80
          encoding:
            codec: json
            except_fields:
              - __host
          batch:
            max_bytes: 524288
          out_of_order_action: rewrite_timestamp
          labels:
            source: talos_service
            hostname: >-
              {{`{{ __host }}`}}
            service: >-
              {{`{{ "talos-service" }}`}}

    podMonitor:
      enabled: true
      jobLabel: vector-aggregator
      port: prometheus-sink

    resources:
      requests:
        cpu: 35m
        memory: 249M
      limits:
        memory: 2G

    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: ${SVC_VECTOR_AGGREGATOR_ADDRESS}
      externalTrafficPolicy: Local

  # postRenderers:
  #   - kustomize:
  #       patchesJson6902:
  #         - target:
  #             kind: Service
  #             name: vector-aggregator
  #           patch:
  #             - op: add
  #               path: /spec/loadBalancerIP
  #               value: ${SVC_VECTOR_AGGREGATOR_ADDRESS}
  #             - op: replace
  #               path: /spec/externalTrafficPolicy
  #               value: Local
