---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/kustomization-kustomize-v1beta2.json
apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
metadata:
  name: storage
  namespace: flux-system
resources:
  - ./multus
  - ./whereabouts
  - ./namespace.yaml
