---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: thanos
      version: 12.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    query:
      enabled: true

      replicaCount: 3
      replicaLabel:
        - __replica__

      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring

      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "false"
        hostname: &host "thanos-query.${SECRET_DOMAIN}"
        tls: true
        extraTls:
          - hosts:
              - *host

      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 99M

    queryFrontend:
      enabled: false

    bucketweb:
      enabled: false
    compactor:
      enabled: false
    storegateway:
      enabled: false
    ruler:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
