---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/kustomization-kustomize-v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - path: patch-rook-ceph-rules.yaml
    target:
      group: monitoring.coreos.com
      version: v1
      kind: PrometheusRule
      name: prometheus-ceph-rules
      namespace: rook-ceph
