# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
    namespace: network
type: Opaque
stringData:
    SMTP_PASSWORD: ENC[AES256_GCM,data:lnWuGCmBbJrQGlDa+qwGcmvQ5WFDM7YTxvYYBWpU0WaFNDFXDxKq8fYcbo7HSLe6+Cw=,iv:THnnzG7ckb080yvXYsUIfeHC3yq3NMYnpwkasCdmm1M=,tag:UyJnQ+VD0v5sc7TjZKAyYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sygu27jssadvgjm86dm0h7p02yzqnp2naxaz3mjrkc4tkek9a35sthss8w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbzRjbzgyRTBtRmZXNHd1
            eDZ4dUxtWndsQURod1NXbGpSQWRnM2RQUkRJCk9OMDdjT2F5azVtSkpHZi9XVzZQ
            N1NkY0xQZ0psUjZjV3ZQSnkzRzNoNE0KLS0tIEdTNEhMZGhLZXYwMllmWThZQlRI
            Q0d6L3dBM3dhSFdSOXZIdkU5ZVBOdGMKVuO66iW6LHx2nMCgKFAEgWgtPD3tj+7x
            6cZrrbCJc94atdXasaIwRuvIfaXGsBINclHxaXajsLRaSMh2yrc5GA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-23T21:21:58Z"
    mac: ENC[AES256_GCM,data:5K/zlz/+ihQcPMVqNlT+zh/DjdLrnjzdlsfWCbDSYdXEctDiUkNFmBL58FFAXhHjZeIOq7v4lFVcZXCWdhTKHa9bF5isD4Avddi554sFnG7xuXPlHsLHwkPRUMjHm6gKGxB4/Sh6AJ5ghl6H643CTPXsDf2LsimmkYfg6/VtkTo=,iv:JhqtikdDTairh+18uP7ZxuyRzUBS8x+9P0L5mg44VD0=,tag:+fI09E8/Oa8W6lLNurzjZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
