---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kubevirt-app
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-kyverno-app
  interval: 10m
  path: ./cluster/apps/kubevirt/kubevirt/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kubevirt-storageprofile
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-kubevirt-app
  interval: 10m
  path: ./cluster/apps/kubevirt/kubevirt/storageprofile
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  timeout: 2m
