---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kubevirt-app
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./cluster/apps/kubevirt/kubevirt/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  timeout: 2m

  patches:
    - target:
        kind: StorageProfile
        name: ceph-block
        namespace: default
      patch: |
        - op: add
          path: /spec
          value:
            claimPropertySets:
              - accessModes:
                  - "ReadWriteOnce"
                volumeMode: "Block"
